### ISSUE TITLE
clean_db_020823.sh invalid container image env variable

### ISSUE THREAD

**Issue by kraymerica-llc** [FindoraNetwork/findora-toolbox#37]
Specifies:
FINDOR_IMG=findoranetwofindorad:${LIVE_VERSION}

Should be:
FINDORAD_IMG=findoranetwork/findorad:${LIVE_VERSION}

**Comment by patrickmogul** [comment]
Fixed the original file and the recent in this push --> https://github.com/FindoraNetwork/findora-toolbox/pull/41
